### ISSUE TITLE
Destroy and Create Scene Again

### ISSUE THREAD

**Issue by smoothboy** [xeolabs/scenejs#199]
I what to destroy a previous scene A and than load a new scene B. A and B have same scene id (like 'Scene'). Here is my code:

var sceneA=SceneJS.scene('Scene');
sceneA.destroy();
sceneA=null;

SceneJs.createScene(json);
var sceneB=SceneJS.scene('Scene');

The console gives: "createScene - scene id 'Scene' already taken by another scene"

It is a bug? or may be there are some way to load new scene again? 

Many thanks!

**Comment by aponyrko** [comment]
I just collided with this. Can't comment on memory usage, but definitely can't reuse a destroyed scene id.
