### ISSUE TITLE
Auto camera aspect from canvas dimensions

### ISSUE THREAD

**Issue by xeolabs** [xeolabs/scenejs#213]
When aspect not specified on camera, derive it dynamically from canvas

**Comment by pavelvasev** [comment]
It seems that when using http://scenejs.org/api/latest/scenejs.js - aspect ratio is good. And when use scenejs.js from Downloads/Zip, aspect ratio is bad.

**Comment by xeolabs** [comment]
Yip I just need to package it in a new release archive, will do that soon

On Mon, Jan 5, 2015 at 4:00 PM, Pavel Vasev <notifications@github.com>
wrote:

> It seems that when using http://scenejs.org/api/latest/scenejs.js -
> aspect ratio is good. And when use scenejs.js from Downloads/Zip, aspect
> ratio is bad.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/issues/213#issuecomment-68718799>.
>



-- 
Lindsay Kay
http://xeolabs.com
