### ISSUE TITLE
Could not change Color for a particular Geometry ID as setColor does not exist

### ISSUE THREAD

**Issue by softwarevikas** [xeolabs/scenejs#335]
Could not change Color for a particular Geometry ID as setColor does not exist, Material Color can be changed but in a Model Multiple Material Instances could be there.

Please let me know how I can change a color on click of a particular geometry.

**Comment by xeolabs** [comment]
You would need to manage your own mapping of the ````name```` node's ````name```` attribute to a root node of a subgraph that wraps both ````material```` and the ````geometry````, then did down from that root to find the ````material````, then set the color on that.
