### ISSUE TITLE
Images are vertically squashed

### ISSUE THREAD

**Issue by Engelberg** [xeolabs/scenejs#344]
I downloaded the 4.0 release zip file, unzipped it, opened the firstExample.html, and the teapot looks squashed.  I pasted in some other geometries and examples from the website, such as the box and the sphere; running locally, all of these objects appear twice as wide as they are high.  I'm getting this behavior in both Firefox and Chrome.

I'm having trouble just getting started since everything looks squashed.  Any idea what is going wrong?

**Comment by xeolabs** [comment]
This is due to the frustum aspect ratio not synchronizing with the canvas - has been fixed in the latest build. I just updated those snapshot archives to include that build - download and try again..

**Comment by xeolabs** [comment]
New release, fixing this problem:
https://github.com/xeolabs/scenejs/releases/tag/v4.0.1
