### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by joeedh** [xeolabs/scenejs#347]
A tree?  A DAG solver? A cyclic dependency graph solver (like Maya)?  I can't find an answer on the website as to what, exactly, scene.js is.  Or am I just blind ;) ?

**Comment by xeolabs** [comment]
On scenejs.com: "SceneJS is an extensible WebGL-based engine for high-detail 3D visualisation using JavaScript."

**Comment by joeedh** [comment]
That doesn't answer my question.  What sort of graph structure does scene.js use?  "extensible WebGL-based engine for high-detail 3D visualization" tells me absolutely nothing.

**Comment by xeolabs** [comment]
It's a DAG in which essentially the geometry node at each leaf represents a
draw call, while the nodes on the path to the root represent the WebGL
state to bind for the call. The geometry leaves are rendered in the order
in which they are defined.

On Tue, Mar 3, 2015 at 8:11 PM, joeedh <notifications@github.com> wrote:

> That doesn't answer my question. What sort of graph structure does
> scene.js use? "extensible WebGL-based engine for high-detail 3D
> visualization" tells me absolutely nothing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/issues/347#issuecomment-77012737>.
>



-- 
Lindsay Kay
http://xeolabs.com
