### ISSUE TITLE
Vertex Color transparency (alpha) is ignored.

### ISSUE THREAD

**Issue by mcukierman** [xeolabs/scenejs#348]
I was trying to modify the example: 
http://scenejs.org/examples/index.html#geometry_vertexColors

After removing textures I've found out that changeing the alpha of the single vertex does not work.
Adding material and/or flag node with transparency enabled makes no difference also.
The basic code is like the following:

```javascript
nodes : [{
		"type" : "flags",
		"flags" : {
			"transparent" : true,
			"enabled" : true
		},
		nodes : [{
			type : "geometry",
			primitive : "triangles",
			positions : [...],
			normals : [...],
			// Color for each vertex
			colors : [
				/* v0-v1-v2-v3 front
				*/
				0.5, 0.0, 0.0, 0.2, /* Note the alpha != 1, what is not reflected in the result */
				0.0, 0.5, 0.0, 0.2,
				0.0, 0.0, 0.5, 0.2,
				0.0, 0.5, 0.0, 0.2,

				/* v0-v3-v4-v5 right
				*/
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,

				/* v0-v1-v2-v3 front
				*/
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,

				/* v0-v3-v4-v5 right
				*/
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,

				/* v0-v1-v2-v3 front
				*/
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,
				0.0, 0.0, 0.0, 1.0,

				/* v0-v3-v4-v5 right
				*/
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0,
				1.0, 1.0, 1.0, 1.0
			],
			indices : [...]
		}],
}]
```
This issue is critical for my case, as most of the geometries exported from third party software are multicolor. Spliting the geometries into separate ones is not the solution, because the geometry has to be handled as a one element (picking, highlighting, disabling).

**Comment by xeolabs** [comment]
Hi Michal, 

yes this is a bug, or more like an incompleteness - only the RGB components of vertex colors are currently used, [see here in the shader generation](https://github.com/xeolabs/scenejs/blob/shader-optimizations/src/core/display/programSourceFactory.js#L648)

It's an easy enough fix, I should be able to fix it this week.

cheers
LK

**Comment by mcukierman** [comment]
Hello Lindsay,

Thanks for your response. Please forgive me direct asking, but was it the status of the issue? I am waiting for the solution, as it's a show stopper for my application. I would be more than happy to contribute, but unfortunately I am Java developer and I am not able to do the implementation. If I can help somehow, I would be more than happy to do so.
Thank you in advance.

Cheers,
Michał

**Comment by xeolabs** [comment]
@jacquesc just fixed this - [here's an example](http://scenejs.org/examples/index.html#geometry_vertexColors_alpha) of how to do transparency using non-zero vertex alphas.
