### ISSUE TITLE
Why does not an orthogonal projection model zoom?

### ISSUE THREAD

**Issue by mirro187** [xeolabs/scenejs#362]
var scene = SceneJS.createScene({
        nodes:[

            // Orbiting camera node, implemented by plugin at
            // http://scenejs.org/api/latest/plugins/node/cameras/orbit.js
            {
                type:"cameras/orbit",
                yaw:30,
                pitch:-30,
                zoom:5,
                zoomSensitivity:1.0,

                nodes:[
                    {
                        type:"camera",
                        optics:{
                            type:"ortho",
                            left:-5,
                            bottom:-5,
                            near:0.1,
                            right:5.0,
                            top:5.0,
                            far:10000
                        },

                        nodes:[

                            // Teapot primitive, implemented by plugin at
                            // http://scenejs.org/api/latest/plugins/node/geometry/teapot.js
                            {
                                type:"geometry/teapot"
                            }
                        ]
                    }
                ]
            }
        ]
    });

**Comment by mirro187** [comment]
var scene = SceneJS.createScene({
nodes:[

        // Orbiting camera node, implemented by plugin at
        // http://scenejs.org/api/latest/plugins/node/cameras/orbit.js
        {
            type:"cameras/orbit",
            yaw:30,
            pitch:-30,
            zoom:5,
            zoomSensitivity:1.0,

            nodes:[
                {
                    type:"camera",
                    optics:{
                        type:"ortho",
                        left:-5,
                        bottom:-5,
                        near:0.1,
                        right:5.0,
                        top:5.0,
                        far:10000
                    },

                    nodes:[

                        // Teapot primitive, implemented by plugin at
                        // http://scenejs.org/api/latest/plugins/node/geometry/teapot.js
                        {
                            type:"geometry/teapot"
                        }
                    ]
                }
            ]
        }
    ]
});

**Comment by xeolabs** [comment]
Can you show us what you're doing to make the "camera" node (which has the ortho projection) zoom?

**Comment by mirro187** [comment]
The example I saw is on this website.
http://scenejs.org/examples/index.html#transforms_projection_ortho

**Comment by xeolabs** [comment]
I don't see where that example is doing any zooming. Can you be specific by what you mean by zooming?

**Comment by xeolabs** [comment]
I figured out what you're asking - the example is zooming, however since orthographic projection gives no sense of perspective reduction with depth, the object remains rendering at the same size within the canvas as the distance from (eye->look) is varied (eg. with mouse wheel).
