### ISSUE TITLE
SceneJS.TextureMap.prototype.setSrc(src) Broken in 4.2

### ISSUE THREAD

**Issue by nym666** [xeolabs/scenejs#367]
There is a big issues in 4.2 with SceneJS.TextureMap.prototype.setSrc function (row 13488):

Row 13492 is         this._loadTexture(src);

but should be something like         this._loadTexture(texture,src);
where texture is somthing type like __proto__: WebGLTexturePrototype

With this issue texture can't be replaced with setSrc function as can be done before

**Comment by tsherif** [comment]
Hmm... I think this is probably related to the texture preload changes I made. I'll look into this.
