### ISSUE TITLE
Get all mesh of obj file ?

### ISSUE THREAD

**Issue by Adwelean** [xeolabs/scenejs#383]
Hello,

I would like to know if is possible to get all the mesh into an obj ?
Because, i have a 3d object (a jacket) with 4 mesh (body, buttons, pockets, collar) and i would modify texture dynamically of each mesh.

Best regards,
Quentin

**Comment by xeolabs** [comment]
Hi, see this example: http://scenejs.org/examples/index.html#importing_obj_raptor

The ````import/obj```` node does not import ````.MTL```` files, so you need to import each mesh using that node, while wrapping each ````import/obj```` node in a ````texture```` node. You can then access each of those ````texture```` nodes to animate it if required.

**Comment by Adwelean** [comment]
Okay, so  if I understand it correctly, i have to extract each mesh of my obj, and put them into another obj and finally load each obj for applying their respective textures.

You validate that ?

Also, I have tried with this structure but not successfully : 
+ nodes [camera]
   + nodes [lights]
      + node [translate]
         + node [texture] { this texture has been applied to each mesh }
            + node [texture] { this texture was not applied }
               + node [import/obj]

Thank for your answer

**Comment by xeolabs** [comment]
Yes that's correct, each mesh needs to be imported independently. That's the limit of out importer until we have one that imports ````MTL```` files as part of the ```OBJ````.

The hierarchy looks OK, but you'd need to post the code live somewhere in order to really tell what's wrong with it.

**Comment by Adwelean** [comment]
Ok thanks :smiley:
