### ISSUE TITLE
Transition between the appearance of 2d and 3d

### ISSUE THREAD

**Issue by ronnyek** [xeolabs/scenejs#386]
Not a bug, not an issue, just a question...

This may be a stretch or even just a limitation of 3d frameworks in general...

I'd like do give the appearance of 2d sideview when camera is aimed at one side of say a cube... and get a square (not seeing depth etc), and only start seeing stuff as 3d as I pan around it. 

I thought I could achieve stuff like this by using isometric cameras and such, but no idea with your framework.

**Comment by xeolabs** [comment]
Yeah you might use an [orthographic projection](http://scenejs.org/examples/index.html#transforms_projection_ortho)
