### ISSUE TITLE
Possible bug - Nodes are not destroyed when they are created and destroyed with big frequency.

### ISSUE THREAD

**Issue by zbysiusiekiera** [xeolabs/scenejs#408]
Hello,

I've a case where I want to create and destroy visual elements with high frequency. While experimenting if it's possible to use SceneJS for this task I have encountered possible bug on Firefox 42.0 where I can not destroy some of the nodes.

I have modified first example to reproduce my problem, but sometimes (like 1/20) it doesn't happen. I create basic scene (code below) with camera to which I periodically add new nodes at random positions and destroy the previous ones. What I expect to see are boxes constantly appearing and dissappearing very frequently, but sometimes some of the boxes (the very first one) will stay forever and can't be destroyed.

When there's more happening in the back in my complete project then the number of not destroyed boxes increases over time cluttering the scene, even if the frequency is much lower than in example below.

Kind regards,
Jakub

```javascript
SceneJS.setConfigs({
        pluginPath:"./plugins"
    });
    var scene = SceneJS.createScene({
        nodes:[
            {
                type:"lookAt",
                eye:{ x:5, y: 5, z: 10 },
                look:{ x:5, y:5, z:0 },
				id: 'myCamera'
            }
        ]
    });
	
	function makeBox() {
		return {
			type: 'translate',
			x: Math.floor((Math.random() * 10) + 1),
			y: Math.floor((Math.random() * 10) + 1),
			z: 0,
			nodes: [{
				type: 'geometry/box',
				size: [0.1, 0.1, 0.1]
			}]
		};
	}
	
	var colors = [
		{ r:0.3, g:0.3, b:1 },
		{ r:0.3, g:1, b:0.3 },
		{ r:1, g:0.3, b:0.3 }
	];
	var color = 0;
	function setPoints() {
		scene.getNode('myCamera', function (camera) {
			camera.nodes.forEach(function (child) {
				child.destroy();
			});
			camera.addNode({
				type: "material",
					color: colors[color],
					nodes: [
						makeBox(), 
						makeBox(), 
						makeBox(), 
						makeBox(), 
						makeBox()
					]
				}, function (newNodes) {
					color = color === 2 ? 0 : color + 1;
				});
		});
	}
	
	setInterval(setPoints, 20);
```

**Comment by tsherif** [comment]
I think the problem is that you're not properly disconnecting those box nodes from the graph. Try changing the `forEach` in your `setPoints` function to the following:

```JavaScript
  camera.nodes.forEach(function (child) {
    child.disconnect();
    child.destroy();
  });
```

**Comment by zbysiusiekiera** [comment]
Thank you, now everything disappears as wanted. In the destroy() code https://github.com/xeolabs/scenejs/blob/master/src/core/scene/node.js#L1351 shouldn't it iterate over parent's nodes? I think this could be the reason of inconsistent behaviour.

**Comment by tsherif** [comment]
That definitely does look like a bug. It's iterating over the parent's node list, but using the length of it's own node list as a stopping condition.

CC: @xeolabs

**Comment by xeolabs** [comment]
Fixed: https://github.com/xeolabs/scenejs/commit/b918003ad38d051e94daf500264bd88a2013a1fa#diff-52ca96f440d36477bdee14b81ae39a81R1349
