### ISSUE TITLE
obj not rendering in a canvas 

### ISSUE THREAD

**Issue by miscbits** [xeolabs/scenejs#409]
so I was trying to follow along with some of the tutorials for a project here, but I could not figure out how to choose the canvas that an obj loads in. 

<img width="643" alt="screen shot 2015-11-09 at 12 39 06 pm" src="https://cloud.githubusercontent.com/assets/8864479/11041292/f3ba4ae2-86de-11e5-816f-21b23cf7d4be.png">
<img width="637" alt="screen shot 2015-11-09 at 12 39 29 pm" src="https://cloud.githubusercontent.com/assets/8864479/11041291/f3b627fa-86de-11e5-8b0b-98919fd7dfa5.png">

here is how the code is written. as you can see I have `canvasId:"stairCanvas"` since I figured that would target the specific canvas I want to get, but on my web page I get nothing rendered. 

<img width="1170" alt="screen shot 2015-11-09 at 12 41 34 pm" src="https://cloud.githubusercontent.com/assets/8864479/11041341/3ece64a0-86df-11e5-8bf9-911d5fb64bbd.png">

so where am I going wrong and where in the documentation should I be looking for this kind of information?

**Comment by miscbits** [comment]
<img width="166" alt="screen shot 2015-11-09 at 12 46 17 pm" src="https://cloud.githubusercontent.com/assets/8864479/11041448/e74f5968-86df-11e5-91e0-4281091f2018.png">
as a side note I definitely have the obj here. Im not getting a not found error on the page

**Comment by xeolabs** [comment]
Look in the examples collection under "Canvas" for examples relating to the canvas: http://scenejs.org/examples/index.html

Your example source code looks OK - could you reproduce this as a [jsFiddle](https://jsfiddle.net/)?

**Comment by miscbits** [comment]
http://codepen.io/anon/pen/pjxXOb
jsFiddle was having some trouble (its still loading in my browser after about 3 minutes) so I did it in codepen if you dont mind. same results anyway

**Comment by miscbits** [comment]
except the obj isn't loading in. sorry. one second

**Comment by miscbits** [comment]
ok new errors. you might have a better time just going to the site url Im having the issue. 

(dev site right now. apologies for the bad styles) 

http://ironbuild.durkancloud.xyz/

**Comment by tsherif** [comment]
It looks like the OBJ loader doesn't understand the OBJ format you're using. The geometry node's arrays are empty.

![screen shot 2015-11-09 at 1 10 56 pm](https://cloud.githubusercontent.com/assets/476017/11042122/689cbd6e-86e3-11e5-8ede-f8b2c34295fd.png)

**Comment by miscbits** [comment]
so this obj was a dwg that was converted to an obj and emailed to me. would the conversion cause that issue or did they just not do something correctly?

**Comment by tsherif** [comment]
Your obj file is completely empty.

![screen shot 2015-11-09 at 1 42 27 pm](https://cloud.githubusercontent.com/assets/476017/11042884/d44ffc16-86e7-11e5-94a2-be6b85bf0af0.png)

**Comment by miscbits** [comment]
yeah we found that just now. we're going to email the client about getting us the right file then.

thanks for the help.
