### ISSUE TITLE
Uncaught TypeError: this.VAO.bindVertexArrayOES is not a function

### ISSUE THREAD

**Issue by tornado96** [xeolabs/scenejs#414]
when i run the example, an error occurred：
Uncaught TypeError: this.VAO.bindVertexArrayOES is not a function
can some one give me help?

**Comment by xeolabs** [comment]
Which example?

**Comment by tornado96** [comment]
http://localhost:8090/scenejs/examples/cameras_orbit.html
Uncaught TypeError: this.VAO.bindVertexArrayOES is not a functionSceneJS_ChunkFactory.createChunkType.draw @ scenejs.js:19486SceneJS_Display._doDrawList @ scenejs.js:17291SceneJS_Display.render @ scenejs.js:16377draw @ scenejs.js:2333window.(anonymous function) @ scenejs.js:2395

**Comment by xeolabs** [comment]
Can you provide a link that's accessible via the web, ie. not at localhost?

**Comment by xeolabs** [comment]
Fixed: https://github.com/xeolabs/scenejs/commit/995a6bbf69c51f5f7b60fdbd26f747a7cf9849d8
