### ISSUE TITLE
Rotate node update seems broken

### ISSUE THREAD

**Issue by KlausBlass** [xeolabs/scenejs#415]
The following does not work in api/latest, but it does in a previous version from before June 2015 --

I change the angle in a Rotate node in the tick loop. It only shows the first change. Logging getAngle() during each tick shows that the angle is correctly updated in the node but not rendered.
I also notice that the space/earth example from Showcase in Examples does not work: the earth does not rotate. This may be the same problem as mine.
[balls.zip](https://github.com/xeolabs/scenejs/files/53220/balls.zip)

**Comment by xeolabs** [comment]
Hey Klaus, could you try this with the latest build? We might have fixed this recently. If it's still a problem, could you post a link to a JSFiddle? Thanks

**Comment by KlausBlass** [comment]
Unfortunately I don't have my original code any longer, because I used a quaternion instead. But since you closed it I suppose you tested it on other cases.
 

    On Monday, February 1, 2016 7:26 PM, Lindsay Kay <notifications@github.com> wrote:
 

 Closed #415.—

**Comment by xeolabs** [comment]
BTW Klaus - are you using batch-update of node attributes? FYI we'll be
removing that in 4.3.0 -
https://github.com/xeolabs/scenejs/wiki/Changes-coming-in-V4.3.0

On Mon, Feb 1, 2016 at 7:44 PM, Klaus Blass <notifications@github.com>
wrote:

> Unfortunately I don't have my original code any longer, because I used a
> quaternion instead. But since you closed it I suppose you tested it on
> other cases.
>
>
> On Monday, February 1, 2016 7:26 PM, Lindsay Kay <notifications@github.com>
> wrote:
>
>
> Closed #415.—
>
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/issues/415#issuecomment-178120701>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by KlausBlass** [comment]
Lindsay, no I'm not using batch-update.
Tell me, what is the best place (here or Facebook) to talk about SceneJS experiences like:
On iPhone (i.e. IOS/Safari) several things don't work, but I have found work-arounds which might be useful to others...

**Comment by xeolabs** [comment]
If you like, you could write about work-arounds on the SceneJS wiki.

Then maybe we could list you as a project contributor?

If that sounds good, we can find out how you can add those wiki pages (I'm
not sure how contributors can do that on github, but I'll look into it
today).

Any info like that is really useful to us - affects all apps built on
SceneJS.

On Wed, Feb 3, 2016 at 9:09 AM, Klaus Blass <notifications@github.com>
wrote:

> Lindsay, no I'm not using batch-update.
> Tell me, what is the best place (here or Facebook) to talk about SceneJS
> experiences like:
> On iPhone (i.e. IOS/Safari) several things don't work, but I have found
> work-arounds which might be useful to others...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/issues/415#issuecomment-179080205>.
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by xeolabs** [comment]
Aha looks like Github lets you create wiki pages in the SceneJS. That's an
option if you're cool with it.

On Wed, Feb 3, 2016 at 9:19 AM, Lindsay Kay <lindsay.kay@xeolabs.com> wrote:

> If you like, you could write about work-arounds on the SceneJS wiki.
>
> Then maybe we could list you as a project contributor?
>
> If that sounds good, we can find out how you can add those wiki pages (I'm
> not sure how contributors can do that on github, but I'll look into it
> today).
>
> Any info like that is really useful to us - affects all apps built on
> SceneJS.
>
> On Wed, Feb 3, 2016 at 9:09 AM, Klaus Blass <notifications@github.com>
> wrote:
>
>> Lindsay, no I'm not using batch-update.
>> Tell me, what is the best place (here or Facebook) to talk about SceneJS
>> experiences like:
>> On iPhone (i.e. IOS/Safari) several things don't work, but I have found
>> work-arounds which might be useful to others...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/xeolabs/scenejs/issues/415#issuecomment-179080205>.
>>
>
>
>
> --
> Lindsay Kay
> http://xeolabs.com
>



-- 
Lindsay Kay
http://xeolabs.com

**Comment by KlausBlass** [comment]
I don't know, Wiki pages have something authorative to them. Some kind of forum might be more adequate. Whewre other people can quickly and informally chime in as well?

**Comment by xeolabs** [comment]
OK let's try the issue tracker for now. I'll talk with a colleague about
this today and we'll see what options we have for forums.

On Wed, Feb 3, 2016 at 9:54 AM, Klaus Blass <notifications@github.com>
wrote:

> I don't know, Wiki pages have something authorative to them. Some kind of
> forum might be more adequate. Whewre other people can quickly and
> informally chime in as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xeolabs/scenejs/issues/415#issuecomment-179099952>.
>



-- 
Lindsay Kay
http://xeolabs.com
