### ISSUE TITLE
Don't at local & hosting

### ISSUE THREAD

**Issue by myplasma** [xeolabs/scenejs#428]
Hi,
I can not import the obj, md2 or 3ds file on the my computer.
Other examples are running.
thank you.

**Comment by xeolabs** [comment]
Need more details before it's possible to look at this:

* Are you loading the example from the web or locally?
* If locally, are you serving the page with a web server?
* Are there any error messages in the JS console?

**Comment by myplasma** [comment]
Yes,
I am loading from locally server and "iis 8.0" version.
But no error messaging and nothing.

**Comment by tsherif** [comment]
All the importing examples work fine for me. See if it works with a different server. I tried both [nano-server](https://www.npmjs.com/package/nano-server) and `python -m SimpleHTTPServer`.
