### ISSUE TITLE
Should node prototypes be modified?

### ISSUE THREAD

**Issue by tsherif** [xeolabs/scenejs#432]
I'm not sure modifying the Node class' `__proto__`, as is done [here](https://github.com/xeolabs/scenejs/blob/master/src/core/scene/node.js#L1217), is a good idea. MDN suggests that this kind of update can have [serious performance consequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto).

**Comment by xeolabs** [comment]
Indeed it could. This would be one of the things I can fix up in the planned refactor. It's used to allow bulk update of properties via calls like ````someNode.set({ foo: "x", bar: "y" })````, which I want to remove in the refactor, so I'll deal with it then.

Note that it will affect efficiency of updates to scene node properties, and won't affect the actual rendering speed.

**Comment by tsherif** [comment]
True. My main concern would be nodes that are updated frequently, e.g. `xform` nodes where you often have many of them getting updated per frame.

**Comment by xeolabs** [comment]
Scheduled for [v5.0](https://github.com/xeolabs/scenejs/wiki/Proposed-changes-for-V5.0#dont-support-batch-setting-of-node-attributes)
