### ISSUE TITLE
Can textures be cached?

### ISSUE THREAD

**Issue by KlausBlass** [xeolabs/scenejs#436]
I need to switch between textures for an object. Can these textures be cached somehow, so they don't get downloaded every time I re-use them?
(hope this is the right place to ask?)
Thanks,
Klaus

**Comment by xeolabs** [comment]
Yes you could load a texture into an HTML Image object, then set that texture node's ````image```` attribute to that Image, rather than set the node's ````src```` attribute to the URL. 

Eg. ````myTexture.image = myImage;```` instead of ````myTexture.src = "foo/bar.jpg";````

**Comment by KlausBlass** [comment]
Great, I'll do it like this!
Thanks,Klaus
 

    On Monday, February 1, 2016 5:49 PM, Lindsay Kay <notifications@github.com> wrote:
 

 Yes you could load a texture into an HTML Image object, then set that texture node's image attribute to that Image, rather than set the node's src attribute to the URL. Eg. myTexture.image = myImage; instead of myTexture.src = "foo/bar.jpg";—
