### ISSUE TITLE
camera plugins don't work any longer - due to removed batch update feature

### ISSUE THREAD

**Issue by KlausBlass** [xeolabs/scenejs#444]
As of today, Feb, 21st 2016, my applications stopped working due to camera nodes still using batch update. On SceneJS.org the plugin links point to old code containing, e.g.
        lookat.set({
            eye: { x: eye.x, y: eye.y, z: -zoom },
            look: { x: look.x, y: look.y, z: look.z },
            up: { x: 0, y: 1, z: 0 }
        });

Where do I find the new plugins version ?

Thanks,
Klaus

**Comment by xeolabs** [comment]
Hi Klaus,  I'd forgotten to update the plugins but Jacqueline caught that
and fixed them yesterday. I'll merge her fixes tomorrow - just use the old
src for now if you can, should work.

**Comment by KlausBlass** [comment]
Ah, good, no hurry.
BTW the bottom paragraph on SceneJS.org shows a plugins link which still points to version 3.1 ...

**Comment by xeolabs** [comment]
All merged now Klaus, plugins link fixed, cheers

**Comment by KlausBlass** [comment]
Really? api/latest/ shows plugins still as 3 months for the last commit.
Where did you merge the modified plugins?

**Comment by tsherif** [comment]
@KlausBlass you can run `grunt snapshot` to copy the latest plugins into the `api/latest` directory.

**Comment by xeolabs** [comment]
I've just run that - snapshot libs and plugins are now built in master and gh-pages,

**Comment by KlausBlass** [comment]
Perfect. Thanks!
