### ISSUE TITLE
.inc() no longer working

### ISSUE THREAD

**Issue by KlausBlass** [xeolabs/scenejs#446]
This is probably not an issue, but I haven't seen any mention that it had been removed:
Previously this was possible:
scene.getNode("myRotation").inc("angle", 1);

Now it gives an error:
TypeError: .inc is not a function

I changed my occurances to:
scene.getNode("myRotation").setAngle(scene.getNode("myRotation").getAngle() +1);

But .inc() was somewhat clearer ...

**Comment by xeolabs** [comment]
Actually those inc methods got removed along with the batch accessors (sorry, forgot to mention that - they were also modifying the node class prototypes so had to go).

BTW for efficiency, you ought to cache that ````rotate```` node to avoid the lookup:
````javascript
var rotate = scene.getNode("myRotation");
rotate.setAngle(rotate.getAngle() +1);
````

**Comment by KlausBlass** [comment]
I see. And yes, I did cache the node reference, but expanded the code in my post for clarity...
 

    On Tuesday, February 23, 2016 8:56 PM, Lindsay Kay <notifications@github.com> wrote:
 

 Actually those inc methods got removed along with the batch accessors (sorry, forgot to mention that - they were also modifying the node class prototypes so had to go).BTW for efficiency, you ought to cache that rotate node to avoid the lookup:var rotate = scene.getNode("myRotation");
rotate.setAngle(rotate.getAngle() +1);—
