### ISSUE TITLE
latest/scenejs.js broken as of August 12th

### ISSUE THREAD

**Issue by KlausBlass** [xeolabs/scenejs#501]
##### Description of the problem 
error message when loading:  "Failed to get a WebGL 2 context - defaulting to WebGL 1."
error message during picking: "TypeError: canvasPos is undefined" in scenejs.js (line 18302, column 13)
...

##### SceneJS version

- [ ] Dev
- [X] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [X] Firefox
- [ ] Internet Explorer
- [X] mobile Safari

##### OS

- [ ] All of them
- [X] Windows
- [ ] Linux
- [ ] Android
- [X] IOS

**Comment by xeolabs** [comment]
Hi Klaus, I fixed picking in master last night, see if the latest snapshot build works for you now.

**Comment by KlausBlass** [comment]
Hi Lindsay,what is the latest snapshot? http://scenejs.org/api/latest/scenejs.js ?If so, this worked well UNTIL last night. Maybe you introduced an error while fixing something?
Regards,Klaus
 

    On Tuesday, September 13, 2016 11:36 AM, Lindsay Kay <notifications@github.com> wrote:
 

 Hi Klaus, I fixed picking in master last night, see if the latest snapshot build works for you now.—

**Comment by xeolabs** [comment]
Yes that's it - can you link to an example at http://scenejs.org/examples that shows the problem?

**Comment by KlausBlass** [comment]
Your "picking" examples actually only show the first error msg: Failed to get a WebGL 2 context - defaulting to WebGL 1.
Picking works in all of them.
I am trying to find out which part of my code provokes the other error. It's not in the pick handler. Even without pick handlers
the error occurs.

--------------------------------------------
On Tue, 9/13/16, Lindsay Kay <notifications@github.com> wrote:

 Subject: Re: [xeolabs/scenejs] latest/scenejs.js broken as of August 12th (#501)
 To: "xeolabs/scenejs" <scenejs@noreply.github.com>
 Cc: "Klaus Blass" <klaus.blass@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, September 13, 2016, 12:40 PM
 
 Yes that's it - can you link
 to an example at http://scenejs.org/examples
 that shows the problem?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by KlausBlass** [comment]
Lindsay, 

I located the problem, but don't know why it throws the error.
It happens in my own camera plugin (attached).
What I did here is this:
When you embed a canvas in a scrolling html page and then pick something,
the pick coordinates do not correspond with the visible location of the picked object.
In order to compensate for embedding and scrolling I call the pick function from within the mouse handlers
with the adjusted coordinates. This worked just perfectly until yesterday.
Now the error

TypeError: canvasPos is undefined                             scenejs.js (Zeile 1911)
pickBufX = canvasPos[0];                                          scenejs.js (Zeile 18302, Spalte 13)

 is thrown when I call this.getScene().pick(x, y) inside the camera plugin (line 122 in my code).

If you can recommend anything based on the modification you have made, that would be terrific!

Klaus


--------------------------------------------
On Tue, 9/13/16, Lindsay Kay <notifications@github.com> wrote:

 Subject: Re: [xeolabs/scenejs] latest/scenejs.js broken as of August 12th (#501)
 To: "xeolabs/scenejs" <scenejs@noreply.github.com>
 Cc: "Klaus Blass" <klaus.blass@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, September 13, 2016, 12:40 PM
 
 Yes that's it - can you link
 to an example at http://scenejs.org/examples
 that shows the problem?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
