### ISSUE TITLE
Failed to get a WebGL context

### ISSUE THREAD

**Issue by RicoLiu** [xeolabs/scenejs#504]
##### Description of the problem 

![qq 20161114142934](https://cloud.githubusercontent.com/assets/12722992/20255413/4794bbcc-aa77-11e6-8366-c686de54c212.png)

What is wrong?

##### SceneJS version

- [ ] Dev
- [ ] Master
- [x] v4.2.0

##### Browser

- [ ] All of them
- [x] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [ ] All of them
- [x] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
What's your GPU?

**Comment by RicoLiu** [comment]
![qq 20161115082625](https://cloud.githubusercontent.com/assets/12722992/20288316/65edacfa-ab0d-11e6-8053-ad9c484b165a.png)

![qq 20161115083022](https://cloud.githubusercontent.com/assets/12722992/20288356/cc8fcbdc-ab0d-11e6-9022-654357fa676b.png)

![qq 20161115083029](https://cloud.githubusercontent.com/assets/12722992/20288363/dc3b711c-ab0d-11e6-90fa-ccbd4a6686f4.png)


Chrome has this error,but Edge works well

**Comment by xeolabs** [comment]
Thanks - does this work? https://get.webgl.org/

**Comment by RicoLiu** [comment]
NO.

> Hmm. While your browser seems to support WebGL, it is disabled or unavailable. If possible, please ensure that you are running the latest drivers for your video card.

**Comment by xeolabs** [comment]
Sorry to say, but it looks like you have may have one of the recently blacklisted GPUs on that particular machine: https://groups.google.com/forum/#!topic/webgl-dev-list/03i2dNQSwqM
