### ISSUE TITLE
Orbit camera plugin does not allow eye, look and up params to be updated

### ISSUE THREAD

**Issue by geniass** [xeolabs/scenejs#507]
##### Description of the problem 
An orbit camera node's parameters cannot be changed after it is created.
For example if the camera is created with `look: {x: 0, y:0, z: 0}`, this cannot be changed later since the plugin's `setLook` method is currently empty. Additionally, the `update` method completely ignores the `look` variable and overwrites it:
```
var eye = [0, 0, zoom];
var look = [0, 0, 0];
var up = [0, 1, 0];
```

##### SceneJS version

- [ ] Dev
- [x] Master
- [ ] ...

##### Browser

- [x] All of them
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer

##### OS

- [x] All of them
- [ ] Windows
- [ ] Linux
- [ ] Android
- [ ] IOS

**Comment by xeolabs** [comment]
Thanks!
